// 主要猫種の日本語(カタカナ)名。猫種名は合成できないため curated な対応表で持つ。
// ここに無い猫種は英語のまま表示する (英語フォールバック)。
// キーは /api/v1/breeds が返す英語の猫種名 (base 集約後) と一致させること。

export const BREED_READING_JA: Record<string, string> = {
  Abyssinian: "アビシニアン",
  "American Curl": "アメリカンカール",
  "American Shorthair": "アメリカンショートヘア",
  "American Wirehair": "アメリカンワイヤーヘア",
  Balinese: "バリニーズ",
  "Balinese-(Javanese)": "バリニーズ（ジャワニーズ）",
  Bengal: "ベンガル",
  Birman: "バーマン",
  Bombay: "ボンベイ",
  "British Longhair": "ブリティッシュロングヘア",
  "British Shorthair": "ブリティッシュショートヘア",
  Burmese: "バーミーズ",
  "Canadian Lop": "カナディアンロップ",
  Chartreux: "シャルトリュー",
  "Colorpoint Shorthair": "カラーポイントショートヘア",
  "Cornish Rex": "コーニッシュレックス",
  Cymric: "サイメリック",
  "Devon Rex": "デボンレックス",
  "Domestic Cat": "ドメスティックキャット",
  "Egyptian Mau": "エジプシャンマウ",
  "European Burmese": "ヨーロピアンバーミーズ",
  Exotic: "エキゾチック",
  "Exotic Longhair": "エキゾチックロングヘア",
  "Havana Brown": "ハバナブラウン",
  "Japanese Bobtail": "ジャパニーズボブテイル",
  Javanese: "ジャワニーズ",
  Kinkaro: "キンカロー",
  Korat: "コラット",
  "La Perm": "ラパーマ",
  Lamkin: "ラムキン",
  "Maine Coon": "メインクーン",
  Manx: "マンクス",
  Minuet: "ミヌエット",
  Munchkin: "マンチカン",
  "Norwegian Forest Cat": "ノルウェージャンフォレストキャット",
  Ocicat: "オシキャット",
  "Oriental Longhair": "オリエンタルロングヘア",
  "Oriental Shorthair": "オリエンタルショートヘア",
  Persian: "ペルシャ",
  Ragamuffin: "ラガマフィン",
  Ragdoll: "ラグドール",
  "Russian Blue": "ロシアンブルー",
  "Scottish Fold": "スコティッシュフォールド",
  "Selkirk Rex": "セルカークレックス",
  Siamese: "シャム",
  Siberian: "サイベリアン",
  Singapura: "シンガプーラ",
  Skookum: "スクークム",
  Snowshoe: "スノーシュー",
  Somali: "ソマリ",
  Sphynx: "スフィンクス",
  Thai: "タイ",
  Tonkinese: "トンキニーズ",
  Toyger: "トイガー",
  "Turkish Angora": "ターキッシュアンゴラ",
  "Turkish Van": "ターキッシュバン",
};
